kind: Deployment
apiVersion: apps/v1
metadata:
  name: nginx-unprivileged
  namespace: testgitops
  labels:
    app: nginx-unprivileged
    app.kubernetes.io/component: nginx-unprivileged
    app.kubernetes.io/instance: nginx-unprivileged
    app.kubernetes.io/name: nginx-unprivileged
    app.kubernetes.io/part-of: nginx-unprivileged-app
    app.openshift.io/runtime-namespace: testgitops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-unprivileged
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx-unprivileged
        deployment: nginx-unprivileged
      annotations:
        openshift.io/generated-by: OpenShiftWebConsole
    spec:
      containers:
        - name: nginx-unprivileged
          image: >-
            image-registry.openshift-image-registry.svc:5000/testgitops/nginx-unprivileged@latest
          ports:
            - containerPort: 8080
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
